
package org.bp.media.exceptions;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.3.2
 * 2021-02-02T23:01:35.570+01:00
 * Generated source version: 3.3.2
 */

@WebFault(name = "Fault", targetNamespace = "http://tv.bp.org/")
public class TV_Fault_Exception extends Exception {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Fault fault;

    public TV_Fault_Exception() {
        super();
    }

    public TV_Fault_Exception(String message) {
        super(message);
    }

    public TV_Fault_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public TV_Fault_Exception(String message, Fault fault) {
        super(message);
        this.fault = fault;
    }

    public TV_Fault_Exception(String message, Fault fault, java.lang.Throwable cause) {
        super(message, cause);
        this.fault = fault;
    }

    public Fault getFaultInfo() {
        return this.fault;
    }
}
