package org.bp.media.clients;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import org.bp.media.model.TV_Fault_Exception;
import org.bp.media.model.TVObjectFactory;
import org.bp.media.model.OrderInfo;
import org.bp.media.model.TVOrder;

/**
 * This class was generated by Apache CXF 3.3.2
 * 2021-02-02T23:01:35.577+01:00
 * Generated source version: 3.3.2
 *
 */
@WebService(targetNamespace = "http://tv.bp.org/", name = "OrderTvService")
@XmlSeeAlso({TVObjectFactory.class})
public interface OrderTvService {

    @WebMethod
    @RequestWrapper(localName = "cancelOrder", targetNamespace = "http://tv.bp.org/", className = "org.bp.media.model.TVCancelOrder")
    @ResponseWrapper(localName = "cancelOrderResponse", targetNamespace = "http://tv.bp.org/", className = "org.bp.media.model.TVCancelOrderResponse")
    @WebResult(name = "return", targetNamespace = "")
    public OrderInfo cancelOrder(

        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    ) throws TV_Fault_Exception;

    @WebMethod
    @RequestWrapper(localName = "orderTV", targetNamespace = "http://tv.bp.org/", className = "org.bp.media.model.OrderTV")
    @ResponseWrapper(localName = "orderTVResponse", targetNamespace = "http://tv.bp.org/", className = "org.bp.media.model.OrderTVResponse")
    @WebResult(name = "return", targetNamespace = "")
    public OrderInfo orderTV(

        @WebParam(name = "arg0", targetNamespace = "")
        TVOrder arg0
    ) throws TV_Fault_Exception;
}
