package org.bp.media.clients;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import org.bp.media.exceptions.Internet_Fault_Exception;
import org.bp.media.model.InternetObjectFactory;
import org.bp.media.model.InternetOrder;
import org.bp.media.model.OrderInfo;

/**
 * This class was generated by Apache CXF 3.3.2
 * 2021-02-05T14:32:34.850+01:00
 * Generated source version: 3.3.2
 *
 */
@WebService(targetNamespace = "http://internet.bp.org/", name = "OrderInternetService")
@XmlSeeAlso({InternetObjectFactory.class})
public interface OrderInternetService {

    @WebMethod
    @RequestWrapper(localName = "orderInternet", targetNamespace = "http://internet.bp.org/", className = "org.bp.media.model.OrderInternet")
    @ResponseWrapper(localName = "orderInternetResponse", targetNamespace = "http://internet.bp.org/", className = "org.bp.media.model.OrderInternetResponse")
    @WebResult(name = "return", targetNamespace = "")
    public OrderInfo orderInternet(

        @WebParam(name = "arg0", targetNamespace = "")
        InternetOrder arg0
    ) throws Internet_Fault_Exception;
    
    @WebMethod
    @RequestWrapper(localName = "getOrderInfo", targetNamespace = "http://internet.bp.org/", className = "org.bp.media.model.InternetGetOrderInfo")
    @ResponseWrapper(localName = "getOrderInfoResponse", targetNamespace = "http://internet.bp.org/", className = "org.bp.media.model.InternetGetOrderInfoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public OrderInfo getOrderInfo(

        @WebParam(name = "arg0", targetNamespace = "")
        OrderInfo arg0
    ) throws Internet_Fault_Exception;

    @WebMethod
    @RequestWrapper(localName = "cancelOrder", targetNamespace = "http://internet.bp.org/", className = "org.bp.media.model.InternetCancelOrder")
    @ResponseWrapper(localName = "cancelOrderResponse", targetNamespace = "http://internet.bp.org/", className = "org.bp.media.model.InternetCancelOrderResponse")
    @WebResult(name = "return", targetNamespace = "")
    public OrderInfo cancelOrder(

        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    ) throws Internet_Fault_Exception;
}
