/*
 * Ordering media micro service
 * Micro service to order media services (TV + internet)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: supportm@bp.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.bp.mediaorderingui.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Gets or Sets InternetBroadband
 */
public enum InternetBroadband {
  ADSL("ADSL"),
  FIBRE_OPTIC("FIBRE_OPTIC"),
  CABLE("CABLE"),
  MOBILE("MOBILE");

  private String value;

  InternetBroadband(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static InternetBroadband fromValue(String text) {
    for (InternetBroadband b : InternetBroadband.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }
}
