/*
 * Ordering media micro service
 * Micro service to order media services (TV + internet)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: supportm@bp.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.bp.mediaorderingui.model;

import java.util.Objects;

import javax.xml.datatype.DatatypeConfigurationException;
import javax.xml.datatype.DatatypeFactory;
import javax.xml.datatype.XMLGregorianCalendar;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * OrderMediaRequest
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-01-25T21:35:40.848+01:00[Europe/Belgrade]")
public class OrderMediaRequest {
	@JsonProperty("household")
	private Household household = null;

	@JsonProperty("tvService")
	private TVService tvService = null;

	@JsonProperty("tvInstallmentDate")
	private XMLGregorianCalendar tvInstallmentDate = null;

	@JsonProperty("internetService")
	private InternetService internetService = null;

	@JsonProperty("internetInstallmentDate")
	private XMLGregorianCalendar internetInstallmentDate = null;

	@JsonProperty("paymentCard")
	private PaymentCard paymentCard = null;

	public OrderMediaRequest household(Household household) {
		this.household = household;
		return this;
	}

	/**
	 * Get household
	 * 
	 * @return household
	 **/
	public Household getHousehold() {
		return household;
	}

	public void setHousehold(Household household) {
		this.household = household;
	}

	public OrderMediaRequest tvService(TVService tvService) {
		this.tvService = tvService;
		return this;
	}

	/**
	 * Get tvService
	 * 
	 * @return tvService
	 **/
	public TVService getTvService() {
		return tvService;
	}

	public void setTvService(TVService tvService) {
		this.tvService = tvService;
	}

	public OrderMediaRequest tvInstallmentDate(String tvInstallmentDate) throws DatatypeConfigurationException {
		this.tvInstallmentDate = DatatypeFactory.newInstance().newXMLGregorianCalendar(tvInstallmentDate);
		return this;
	}

	/**
	 * Get tvInstallmentDate
	 * 
	 * @return tvInstallmentDate
	 **/
	public XMLGregorianCalendar getTvInstallmentDate() {
		return tvInstallmentDate;
	}

	public void setTvInstallmentDate(String tvInstallmentDate) throws DatatypeConfigurationException {
		this.tvInstallmentDate = DatatypeFactory.newInstance().newXMLGregorianCalendar(tvInstallmentDate);
	}

	public OrderMediaRequest internetService(InternetService internetService) {
		this.internetService = internetService;
		return this;
	}

	/**
	 * Get internetService
	 * 
	 * @return internetService
	 **/
	public InternetService getInternetService() {
		return internetService;
	}

	public void setInternetService(InternetService internetService) {
		this.internetService = internetService;
	}

	public OrderMediaRequest internetInstallmentDate(String internetInstallmentDate)
			throws DatatypeConfigurationException {
		this.internetInstallmentDate = DatatypeFactory.newInstance().newXMLGregorianCalendar(internetInstallmentDate);
		return this;
	}

	/**
	 * Get internetInstallmentDate
	 * 
	 * @return internetInstallmentDate
	 **/
	public XMLGregorianCalendar getInternetInstallmentDate() {
		return internetInstallmentDate;
	}

	public void setInternetInstallmentDate(String internetInstallmentDate) throws DatatypeConfigurationException {
		this.internetInstallmentDate = DatatypeFactory.newInstance().newXMLGregorianCalendar(internetInstallmentDate);
	}

	public OrderMediaRequest paymentCard(PaymentCard paymentCard) {
		this.paymentCard = paymentCard;
		return this;
	}

	/**
	 * Get paymentCard
	 * 
	 * @return paymentCard
	 **/
	public PaymentCard getPaymentCard() {
		return paymentCard;
	}

	public void setPaymentCard(PaymentCard paymentCard) {
		this.paymentCard = paymentCard;
	}

	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		OrderMediaRequest orderMediaRequest = (OrderMediaRequest) o;
		return Objects.equals(this.household, orderMediaRequest.household)
				&& Objects.equals(this.tvService, orderMediaRequest.tvService)
				&& Objects.equals(this.tvInstallmentDate, orderMediaRequest.tvInstallmentDate)
				&& Objects.equals(this.internetService, orderMediaRequest.internetService)
				&& Objects.equals(this.internetInstallmentDate, orderMediaRequest.internetInstallmentDate)
				&& Objects.equals(this.paymentCard, orderMediaRequest.paymentCard);
	}

	@Override
	public int hashCode() {
		return Objects.hash(household, tvService, tvInstallmentDate, internetService, internetInstallmentDate,
				paymentCard);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class OrderMediaRequest {\n");

		sb.append("    household: ").append(toIndentedString(household)).append("\n");
		sb.append("    tvService: ").append(toIndentedString(tvService)).append("\n");
		sb.append("    tvInstallmentDate: ").append(toIndentedString(tvInstallmentDate)).append("\n");
		sb.append("    internetService: ").append(toIndentedString(internetService)).append("\n");
		sb.append("    internetInstallmentDate: ").append(toIndentedString(internetInstallmentDate)).append("\n");
		sb.append("    paymentCard: ").append(toIndentedString(paymentCard)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
