/*
 * Ordering media micro service
 * Micro service to order media services (TV + internet)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: supportm@bp.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.bp.mediaorderingui.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * PaymentCard
 */

@JsonIgnoreProperties(ignoreUnknown = true)
public class PaymentCard {

	private String name;
	private String validTo;
	private String number;

	public PaymentCard name(String name) {
		this.name = name;
		return this;
	}

	/**
	 * Get name
	 * 
	 * @return name
	 **/
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public PaymentCard validTo(String validTo) {
		this.validTo = validTo;
		return this;
	}

	/**
	 * Get validTo
	 * 
	 * @return validTo
	 **/
	public String getValidTo() {
		return validTo;
	}

	public void setValidTo(String validTo) {
		this.validTo = validTo;
	}

	public PaymentCard number(String number) {
		this.number = number;
		return this;
	}

	/**
	 * Get number
	 * 
	 * @return number
	 **/
	public String getNumber() {
		return number;
	}

	public String getMaskedNumber() {
		return number.substring(0, 2) + "****" + number.substring(number.length() - 2);
	}

	public void setNumber(String number) {
		this.number = number;
	}

	@Override
	public boolean equals(java.lang.Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		PaymentCard paymentCard = (PaymentCard) o;
		return Objects.equals(this.name, paymentCard.name) && Objects.equals(this.validTo, paymentCard.validTo)
				&& Objects.equals(this.number, paymentCard.number);
	}

	@Override
	public int hashCode() {
		return Objects.hash(name, validTo, number);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class PaymentCard {\n");

		sb.append("    name: ").append(toIndentedString(name)).append("\n");
		sb.append("    validTo: ").append(toIndentedString(validTo)).append("\n");
		sb.append("    number: ").append(toIndentedString(number)).append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private String toIndentedString(java.lang.Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

}
