/*
 * Ordering media micro service
 * Micro service to order media services (TV + internet)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: supportm@bp.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.bp.media.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
/**
 * InternetService
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-01-25T21:35:40.848+01:00[Europe/Belgrade]")
public class InternetService {
  @JsonProperty("provider")
  private String provider = null;

  @JsonProperty("broadband")
  private InternetBroadband broadband = null;

  @JsonProperty("speed")
  private Integer speed = null;

  public InternetService provider(String provider) {
    this.provider = provider;
    return this;
  }

   /**
   * Get provider
   * @return provider
  **/
  public String getProvider() {
    return provider;
  }

  public void setProvider(String provider) {
    this.provider = provider;
  }

  public InternetService broadband(InternetBroadband broadband) {
    this.broadband = broadband;
    return this;
  }

   /**
   * Get broadband
   * @return broadband
  **/
  public InternetBroadband getBroadband() {
    return broadband;
  }

  public void setBroadband(InternetBroadband broadband) {
    this.broadband = broadband;
  }

  public InternetService speed(Integer speed) {
    this.speed = speed;
    return this;
  }

   /**
   * Get speed
   * @return speed
  **/
  public Integer getSpeed() {
    return speed;
  }

  public void setSpeed(Integer speed) {
    this.speed = speed;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InternetService internetService = (InternetService) o;
    return Objects.equals(this.provider, internetService.provider) &&
        Objects.equals(this.broadband, internetService.broadband) &&
        Objects.equals(this.speed, internetService.speed);
  }

  @Override
  public int hashCode() {
    return Objects.hash(provider, broadband, speed);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InternetService {\n");
    
    sb.append("    provider: ").append(toIndentedString(provider)).append("\n");
    sb.append("    broadband: ").append(toIndentedString(broadband)).append("\n");
    sb.append("    speed: ").append(toIndentedString(speed)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
