
package org.bp.media.model;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.3.2
 * 2021-02-05T14:32:34.843+01:00
 * Generated source version: 3.3.2
 */

@WebFault(name = "Fault", targetNamespace = "http://internet.bp.org/")
public class Internet_Fault_Exception extends Exception {

    private Fault fault;

    public Internet_Fault_Exception() {
        super();
    }

    public Internet_Fault_Exception(String message) {
        super(message);
    }

    public Internet_Fault_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public Internet_Fault_Exception(String message, Fault fault) {
        super(message);
        this.fault = fault;
    }

    public Internet_Fault_Exception(String message, Fault fault, java.lang.Throwable cause) {
        super(message, cause);
        this.fault = fault;
    }

    public Fault getFaultInfo() {
        return this.fault;
    }
}
