/*
 * Ordering media micro service
 * Micro service to order media services (TV + internet)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: supportm@bp.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.bp.media.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import org.bp.media.model.Household;
import org.bp.media.model.TVService;
/**
 * OrderTVRequest
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-01-25T21:35:40.848+01:00[Europe/Belgrade]")
public class OrderTVRequest {
  @JsonProperty("household")
  private Household household = null;

  @JsonProperty("tvService")
  private TVService tvService = null;

  @JsonProperty("installmentDate")
  private OffsetDateTime installmentDate = null;

  public OrderTVRequest household(Household household) {
    this.household = household;
    return this;
  }

   /**
   * Get household
   * @return household
  **/
  public Household getHousehold() {
    return household;
  }

  public void setHousehold(Household household) {
    this.household = household;
  }

  public OrderTVRequest tvService(TVService tvService) {
    this.tvService = tvService;
    return this;
  }

   /**
   * Get tvService
   * @return tvService
  **/
  public TVService getTvService() {
    return tvService;
  }

  public void setTvService(TVService tvService) {
    this.tvService = tvService;
  }

  public OrderTVRequest installmentDate(OffsetDateTime installmentDate) {
    this.installmentDate = installmentDate;
    return this;
  }

   /**
   * Get installmentDate
   * @return installmentDate
  **/
  public OffsetDateTime getInstallmentDate() {
    return installmentDate;
  }

  public void setInstallmentDate(OffsetDateTime installmentDate) {
    this.installmentDate = installmentDate;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrderTVRequest orderTVRequest = (OrderTVRequest) o;
    return Objects.equals(this.household, orderTVRequest.household) &&
        Objects.equals(this.tvService, orderTVRequest.tvService) &&
        Objects.equals(this.installmentDate, orderTVRequest.installmentDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(household, tvService, installmentDate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrderTVRequest {\n");
    
    sb.append("    household: ").append(toIndentedString(household)).append("\n");
    sb.append("    tvService: ").append(toIndentedString(tvService)).append("\n");
    sb.append("    installmentDate: ").append(toIndentedString(installmentDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
