/*
 * Ordering media micro service
 * Micro service to order media services (TV + internet)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: supportm@bp.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package org.bp.media.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import org.bp.media.model.Household;
import org.bp.media.model.InternetService;
/**
 * OrderInternetRequest
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-01-25T21:35:40.848+01:00[Europe/Belgrade]")
public class OrderInternetRequest {
  @JsonProperty("household")
  private Household household = null;

  @JsonProperty("internetService")
  private InternetService internetService = null;

  @JsonProperty("installmentDate")
  private OffsetDateTime installmentDate = null;

  public OrderInternetRequest household(Household household) {
    this.household = household;
    return this;
  }

   /**
   * Get household
   * @return household
  **/
  public Household getHousehold() {
    return household;
  }

  public void setHousehold(Household household) {
    this.household = household;
  }

  public OrderInternetRequest internetService(InternetService internetService) {
    this.internetService = internetService;
    return this;
  }

   /**
   * Get internetService
   * @return internetService
  **/
  public InternetService getInternetService() {
    return internetService;
  }

  public void setInternetService(InternetService internetService) {
    this.internetService = internetService;
  }

  public OrderInternetRequest installmentDate(OffsetDateTime installmentDate) {
    this.installmentDate = installmentDate;
    return this;
  }

   /**
   * Get installmentDate
   * @return installmentDate
  **/
  public OffsetDateTime getInstallmentDate() {
    return installmentDate;
  }

  public void setInstallmentDate(OffsetDateTime installmentDate) {
    this.installmentDate = installmentDate;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrderInternetRequest orderInternetRequest = (OrderInternetRequest) o;
    return Objects.equals(this.household, orderInternetRequest.household) &&
        Objects.equals(this.internetService, orderInternetRequest.internetService) &&
        Objects.equals(this.installmentDate, orderInternetRequest.installmentDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(household, internetService, installmentDate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrderInternetRequest {\n");
    
    sb.append("    household: ").append(toIndentedString(household)).append("\n");
    sb.append("    internetService: ").append(toIndentedString(internetService)).append("\n");
    sb.append("    installmentDate: ").append(toIndentedString(installmentDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
